[workspace]
resolver = "2"

default-members = [
    "app",
]

members = [
    "app",
    "package",
    "xtask",
]

[workspace.dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
socket2 = { version = "0.4.7", features = ["all"] }
